version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "127.0.0.1:80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: docker
      WORDPRESS_DB_PASSWORD: docker
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./_wordpress/html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - wordpress-mysql:/var/lib/mysql

volumes:
  wordpress-mysql:
